 CREATE DATABASE BD_ACADEMIA;
 
 USE BD_ACADEMIA;

CREATE TABLE USERS(
	ID_USERS INT NOT NULL,
	NOME VARCHAR(20),
	SENHA VARCHAR(10),
	ENDERECO VARCHAR(20),
    DOCUMENTO INT(15),
    DATA_NASC DATE,
    PESO NUMERIC(3,3),
    ALTURA NUMERIC(4),
    PRIVILEGIO varchar(1),
    CONSTRAINT PK_USERS PRIMARY KEY (ID_USERS));

CREATE TABLE EXERCICIO(
	ID_EXERCICIO INT NOT NULL,
    NOME varchar(10),
    DESCRICAO VARCHAR(20),
    ID_CATEGORIA INT NOT NULL,
    CONSTRAINT PK_EXERCICIO PRIMARY KEY (ID_EXERCICIO));

CREATE TABLE CATEGORIA(
	ID_CATEGORIA INT NOT NULL,
    NOME VARCHAR(10),
    CONSTRAINT PK_CATEGORIA PRIMARY KEY (ID_CATEGORIA));

CREATE TABLE TREINO(
	ID_TREINO INT NOT NULL,
    SERIE varchar(10),
    DIA varchar(10),
    ID_EXERCICIO INT NOT NULL,
    ID_USERS INT NOT NULL,
    constraint PK_TREINO PRIMARY KEY (ID_TREINO));

ALTER TABLE EXERCICIO
ADD CONSTRAINT FK_EXERCICIO_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA);
    
ALTER TABLE TREINO
ADD CONSTRAINT FK_TREINO_EXERCICIO FOREIGN KEY (ID_EXERCICIO) REFERENCES EXERCICIO(ID_EXERCICIO);

ALTER TABLE TREINO
ADD CONSTRAINT FK_TREINO_USERS FOREIGN KEY (ID_USERS) REFERENCES USERS(ID_USERS);


   