 CREATE DATABASE BD_ACADEMIA;
 
 USE BD_ACADEMIA;
 
 CREATE TABLE USER_MASTER(
	ID_USER INT NOT NULL,
	NOME VARCHAR(20),
	SENHA VARCHAR(10),
	PREVILEGIO VARCHAR(1),
    CONSTRAINT PK_USER PRIMARY KEY (ID_USER));


CREATE TABLE CLIENTE(
	ID_CLIENTE INT NOT NULL,
	NOME VARCHAR(20),
	SENHA VARCHAR(10),
	ENDERECO VARCHAR(20),
    DOCUMENTO INT(15),
    CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE));

CREATE TABLE EXERCICIO(
	ID_EXERCICIO INT NOT NULL,
    NOME varchar(10),
    DESCRICAO VARCHAR(20),
    CONSTRAINT PK_EXERCICIO PRIMARY KEY (ID_EXERCICIO));
    
CREATE TABLE DIA(
	ID_DIA INT NOT NULL,
    DIA_SEMANA VARCHAR(10),
    CONSTRAINT PK_DIA PRIMARY KEY (ID_DIA));
    

CREATE TABLE TREINO(
	ID_TREINO INT NOT NULL,
    SERIE varchar(10),
    ID_EXERCICIO INT NOT NULL,
    ID_DIA INT NOT NULL,
    ID_CLIENTE INT NOT NULL,
    constraint PK_TREINO PRIMARY KEY (ID_TREINO));
    
ALTER TABLE TREINO
ADD CONSTRAINT FK_TREINO_EXERCICIO FOREIGN KEY (ID_EXERCICIO) REFERENCES EXERCICIO(ID_EXERCICIO);

ALTER TABLE TREINO
ADD CONSTRAINT FK_TREINO_DIA FOREIGN KEY (ID_DIA) REFERENCES DIA(ID_DIA);

ALTER TABLE TREINO
ADD CONSTRAINT FK_TREINO_SERIE FOREIGN KEY (ID_SERIE) REFERENCES SERIE(ID_SERIE);

ALTER TABLE TREINO
ADD CONSTRAINT FK_TREINO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE);


   