CREATE DATABASE BD_LOJA;

USE BD_LOJA;

CREATE TABLE USER_MASTER(
	ID_USER INT NOT NULL,
	NOME VARCHAR(20),
	SENHA VARCHAR(10),
	PREVILEGIO VARCHAR(1),
    CONSTRAINT PK_USER PRIMARY KEY (ID_USER));


CREATE TABLE CLIENTE(
	ID_CLIENTE INT NOT NULL,
	NOME VARCHAR(20),
	SENHA VARCHAR(10),
	ENDERECO VARCHAR(20),
    DOCUMENTO INT(15),
    CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE));
 

CREATE TABLE PRODUTO(
	ID_PRODUTO INT NOT NULL,
	NOME VARCHAR(20),
	PRECO NUMERIC(10,2),
	QTDE INT (5),
    DESCRICAO VARCHAR(50),
    ID_CATEGORIA INT NOT NULL,
    CONSTRAINT PK_PRODUTO PRIMARY KEY (ID_PRODUTO));

CREATE TABLE PEDIDO(
	ID_PEDIDO INT NOT NULL,
	END_ENTREGA VARCHAR(20),
	ID_PRODUTO INT NOT NULL,
    ID_CLIENTE INT NOT NULL,
    CONSTRAINT PK_PEDIDO PRIMARY KEY (ID_PEDIDO));
    
create table PRODUTO_PEDIDO(
	ID_PRODUTO INT NOT NULL,
    ID_PEDIDO INT NOT NULL,
    CONSTRAINT PK_PRODUTO_PEDIDO PRIMARY KEY(ID_PRODUTO, ID_PEDIDO));
    

CREATE TABLE CATEGORIA(
    ID_CATEGORIA INT NOT NULL,
    NOME VARCHAR(10),
    CONSTRAINT PK_CATEGORIA PRIMARY KEY (ID_CATEGORIA));

ALTER TABLE PRODUTO
ADD CONSTRAINT FK_PRODUTO_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA);

ALTER TABLE PEDIDO
ADD CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE);

ALTER TABLE PRODUTO_PEDIDO
ADD CONSTRAINT FK_PRODUTO_PEDIDO1 FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO);

ALTER TABLE PRODUTO_PEDIDO
ADD CONSTRAINT FK_PRODUTO_PEDIDO2 FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO);



 